# Generated by Django 2.2.1 on 2019-05-11 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='provider',
        ),
        migrations.AddField(
            model_name='provider',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.Contract'),
        ),
    ]
