# Generated by Django 2.2.1 on 2019-05-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_auto_20190511_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='contract',
        ),
        migrations.AddField(
            model_name='provider',
            name='contract',
            field=models.ManyToManyField(blank=True, to='providers.Contract'),
        ),
    ]
