# Generated by Django 2.2.1 on 2019-05-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20190511_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
