# Generated by Django 2.2.1 on 2019-06-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_auto_20190511_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.Contract'),
        ),
    ]
