# Generated by Django 2.2.1 on 2019-06-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_auto_20190610_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='percentage',
            field=models.FloatField(blank=True),
        ),
    ]
