# Generated by Django 2.2.1 on 2019-06-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_auto_20190610_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateEnd',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='notification',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
