# Generated by Django 2.2.1 on 2019-06-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_auto_20190617_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateLimit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
