# Generated by Django 2.2.1 on 2019-06-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_auto_20190617_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='in_charge_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='quality_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
