# Generated by Django 2.2.1 on 2019-06-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0012_auto_20190618_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
