# Generated by Django 2.2.1 on 2019-06-19 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_auto_20190618_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='contract',
        ),
        migrations.AddField(
            model_name='contract',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_providers', to='providers.Provider'),
        ),
    ]
