# Generated by Django 2.2.1 on 2019-06-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0014_auto_20190619_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='fulfillment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='satisfaction',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
