# Generated by Django 2.2.1 on 2019-06-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0015_auto_20190619_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='fulfillment',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
