# Generated by Django 2.2.2 on 2019-06-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0017_auto_20190625_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dateEnd',
            field=models.DateField(blank=True, null=True, verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dateStart',
            field=models.DateField(blank=True, null=True, verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dateEnd',
            field=models.DateField(blank=True, null=True, verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dateLimit',
            field=models.DateField(blank=True, null=True, verbose_name='%d/%m/%Y'),
        ),
    ]
