# Generated by Django 2.2.2 on 2019-06-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0018_auto_20190627_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='ruc',
            field=models.CharField(max_length=11),
        ),
    ]
