# Generated by Django 2.2.2 on 2019-06-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0019_auto_20190627_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='supplier_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
