# Generated by Django 2.2.2 on 2019-06-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0020_contract_supplier_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='quality_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
