# Generated by Django 2.2.2 on 2019-06-29 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0021_auto_20190629_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='suppliers',
        ),
        migrations.AddField(
            model_name='supplier',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_provider', to='providers.Provider'),
        ),
    ]
