# Generated by Django 2.2.2 on 2019-09-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0023_auto_20190629_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
